src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Webmozart\Assert\Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity('pseudo', message: 'Ce pseudo est déjà utilisé')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column()]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255, unique: true, nullable: true)]
    private ?string $pseudo = null;

    #[ORM\Column(length: 10)]
    private ?string $telephone = null;

    #[ORM\OneToMany(mappedBy: 'organisateur', targetEntity: Sortie::class)]
    private Collection $sortiesOrganises;

    #[ORM\ManyToMany(targetEntity: Sortie::class, mappedBy: 'participants')]
    private Collection $sorties;

    #[ORM\ManyToOne(inversedBy: 'users')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Site $site = null;

    #[ORM\Column]
    private ?bool $isAdministrateur = false;

    #[ORM\Column]
    private ?bool $isActif = true;

    #[ORM\Column(length: 255)]
    private ?string $photo = null;

    private $plainPassword;

    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    public function setPlainPassword(?string $plainPassword): void
    {
        $this->plainPassword = $plainPassword;
    }

    public function __construct()
    {
        $this->sortiesOrganises = new ArrayCollection();
        $this->sorties = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getPseudo(): ?string
    {
        if ($this->pseudo == null)
            return "Non renseigné";

        return $this->pseudo;
    }

    public function setPseudo(?string $pseudo): static
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    /**
     * @return Collection<int, Sortie>
     */
    public function getSortiesOrganises(): Collection
    {
        return $this->sortiesOrganises;
    }

    public function addSortiesOrganise(Sortie $sortiesOrganise): static
    {
        if (!$this->sortiesOrganises->contains($sortiesOrganise)) {
            $this->sortiesOrganises->add($sortiesOrganise);
            $sortiesOrganise->setOrganisateur($this);
        }

        return $this;
    }

    public function removeSortiesOrganise(Sortie $sortiesOrganise): static
    {
        if ($this->sortiesOrganises->removeElement($sortiesOrganise)) {
            // set the owning side to null (unless already changed)
            if ($sortiesOrganise->getOrganisateur() === $this) {
                $sortiesOrganise->setOrganisateur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Sortie>
     */
    public function getSorties(): Collection
    {
        return $this->sorties;
    }

    public function addSorty(Sortie $sorty): static
    {
        if (!$this->sorties->contains($sorty)) {
            $this->sorties->add($sorty);
            $sorty->addParticipant($this);
        }

        return $this;
    }

    public function removeSorty(Sortie $sorty): static
    {
        if ($this->sorties->removeElement($sorty)) {
            $sorty->removeParticipant($this);
        }

        return $this;
    }

    public function getSite(): ?Site
    {
        return $this->site;
    }

    public function setSite(?Site $site): static
    {
        $this->site = $site;

        return $this;
    }

    public function isIsAdministrateur(): ?bool
    {
        return $this->isAdministrateur;
    }

    public function setIsAdministrateur(bool $isAdministrateur): static
    {
        $this->isAdministrateur = $isAdministrateur;

        return $this;
    }

    public function isIsActif(): ?bool
    {
        return $this->isActif;
    }

    public function setIsActif(bool $isActif): static
    {

        $this->isActif = $isActif;

        return $this;
    }

    public function getFullName():string
    {
        return $this->prenom.' '.strtoupper($this->nom);
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): static
    {
        $this->photo = $photo;

        return $this;
    }
}

templates/fragments/footer.html.twig
<footer>

    © Eni-Sortir {{ 'now' | date('Y')}}


</footer>

templates/fragments/header.html.twig
<header>
    <nav class="navbar navbar-expand-lg " >
        <div class="container-fluid" >
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <a href="{{ path('app_sortie_index') }}">
                    <img src="{{ asset('images/logo eni.png') }}" alt="" width="80px"></a>
                    <ul class="navbar-nav">

                        {% if app.user %}
                            <li class="nav-item">
                                <a class="nav-link text-light" href="{{ path('app_sortie_index') }}">Accueil
                                    <span class="visually-hidden">(current)</span>
                                </a>
                            </li>
                        {% endif %}

                        {% if is_granted('ROLE_ADMIN') %}
                            <li class="nav-item">
                                <a class="nav-link text-light " href="{{ path('admin')}}">Espace Admin
                                    <span class="visually-hidden">(current)</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
                        {% if app.user %}
                            <a href="{{ path('app_sortie_new') }}" id="creation" class="btn  buttonBlancBleu m-3">Créer Sortie</a>
                            <p class="text-light">{{ app.user.fullName }}</p>
                            <ul>

                                <li class="nav-item list-unstyled">

                                    <a href=""><svg xmlns="http://www.w3.org/2000/svg" height="2em" viewBox="0 0 448 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><style>svg{fill:#ffffff}</style><path d="M224 256A128 128 0 1 0 224 0a128 128 0 1 0 0 256zm-45.7 48C79.8 304 0 383.8 0 482.3C0 498.7 13.3 512 29.7 512H418.3c16.4 0 29.7-13.3 29.7-29.7C448 383.8 368.2 304 269.7 304H178.3z"/></svg></a>
                                    <ul>
                                        <li><a href="{{ path('app_user_show', {'id': app.user.id}) }}">Mon profil</a></li>
                                        <li><a href="{{ path('app_logout') }}">Deconnexion</a></li>

                                    </ul>
                                </li>
                            </ul>
                        {% endif %}
            </div>
    </nav>

</header>